### overview localhost
GET http://localhost:4566/health

### get table
GET http://localhost:3000/tables?tableName=sdk
Content-Type: application/json

### insert item on table
POST http://localhost:3000/tables?tableName=sdksTable
Content-Type: application/json

{
    "key": "test2",
    "payload": "{}"
}