service: sls-sqs-ts-example
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_SESSION_TOKEN: ${env:AWS_SESSION_TOKEN}
    AWS_REGION: ${aws:region}

functions:
  tables:
    handler: ./src/tables.get
    events:
      - httpApi:
          path: /tables
          method: get
  insertTable:
    handler: ./src/tables.postItem
    events:
      - httpApi:
          path: /tables
          method: post

custom:
  esbuild:
    minify: false
    sourcemap: linked
    watch:
      pattern: "src/**/*.ts"
      ignore: "node_modules/**/*"

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
