service: sls-sqs-ts-example
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_SESSION_TOKEN: ${env:AWS_SESSION_TOKEN}
    AWS_REGION: ${aws:region}

functions:
  s3TriggerFunction:
    handler: src/handler.execute
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:Put
          existing: true

custom:
  esbuild:
    minify: false
    sourcemap: linked
    watch:
      pattern: "src/**/*.ts"
      ignore: "node_modules/**/*"
  s3:
    directory: ./buckets

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-s3-local
  - serverless-offline