service: sls-sqs-ts-example
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_SESSION_TOKEN: ${env:AWS_SESSION_TOKEN}
    AWS_REGION: ${aws:region}

functions:
  scheduled-jobs:
    handler: ./src/scheduled-handler.handler
    events:
      - schedule:
          name: monthly-job-schedule
          description: 'Executa job mensal no último dia do mês às 18h (São Paulo)'
          rate: cron(21 18 L * ? *)
          timezone: America/Sao_Paulo
          input:
            jobType: monthly
      - schedule:
          name: weekly-job-schedule
          description: 'Executa job semanal toda sexta-feira às 18h (São Paulo)'
          rate: cron(21 18 ? * THU *)
          timezone: America/Sao_Paulo
          input:
            jobType: weekly

custom:
  esbuild:
    minify: false
    sourcemap: linked
    watch:
      pattern: "src/**/*.ts"
      ignore: "node_modules/**/*"

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
